### ISSUE TITLE
A possible and easiest solution if it works

### ISSUE THREAD

**Issue by nxjosephofficial** [nxjosephofficial/primevideo-linux#7]
Hello. I don't have primevideo account so I can't try this myself. If you want to help me, it's appreciated!

Basically, you are changing your `Linux` user agent with a `Windows` one on Firefox browser. I saw a guide about watching Disney Plus on Linux and this came to my mind. If it works for primevideo, it'll be nice and easiest solution.

[Full guide](https://linuxconfig.org/how-to-watch-disney-plus-on-linux-with-firefox)

### Steps
1. Check DRM Content on Firefox settings
2. On Windows, learn your user agent by typing this javascript command to your browser's developer console.
`navigator.userAgent;`
3. It should give you something like this.
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
`
4. Save your `Windows` user agent to use it on Linux.
5. Go to `about:config` on Firefox.
6. Right click somewhere in the blank space of the window. When the menu opens, choose New followed by String then enter the following.
`general.useragent.override.primevideo.com
`
7. It's easy to understand by reading this string, makes a user agent override for a specified website.
8. Now enter your `Windows` user agent to `Value` of your `String` and save it.
9. Try watching [primevideo](https://primevideo.com) on HD quality.

If you don't have `Windows` which you can get it's user agent, I took a user agent a week ago from my `Windows`.
`
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
`

**Comment by eathtespagheti** [comment]
This method doesn't work, I've already tried several times

**Comment by nxjosephofficial** [comment]
Thank you for quick reply and feedback.
