### ISSUE TITLE
Çok teşekkür ederim abi

### ISSUE THREAD

**Issue by berkaydagdeviren** [nxjosephofficial/primevideo-linux#8]
Gerçekten çok teşekkürler exxende "this content is currently unavailable" sorunumu çözdüm. --no-sandbox parametresiyle çalıştırmadan da oldu bende

**Comment by berkaydagdeviren** [comment]
tertemiz çalışıyorkan şimdi yine aynı hatayı alıyorum...

**Comment by nxjosephofficial** [comment]
Merhaba. Wine'ın son sürümü bir şeyleri bozdu sanırım ama emin değilim. En son wine sürümü 7.21, bir önceki wine sürümü olan  7.20 ile deneyebilirsiniz.

Hangi dağıtımı kullanıyorsunuz?

**Comment by berkaydagdeviren** [comment]
ubuntu kullanıyorum abi

**Comment by berkaydagdeviren** [comment]
sürümüm şuan 7.20 olarak gözüküyor

**Comment by nxjosephofficial** [comment]
Ubuntu'nun sürümü kaç?

> 
sürümüm şuan 7.20 olarak gözüküyor

Bunu beklemiyordum, 7.19 deneyelim.

**Comment by berkaydagdeviren** [comment]
Ubuntu 22.04.1 LTS

**Comment by nxjosephofficial** [comment]
Teşekkür ederim.

Sisteminizde wget yüklü ise kolay bir şekilde aşağıdaki komut ile wine 7.19'u deneyin.
```
wget https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-amd64/wine-staging-amd64_7.19~jammy-1_amd64.deb /
sudo apt install ./wine-staging-amd64_7.19~jammy-1_amd64.deb
```
